PLAT-4483: scaffold: make Android App Bundle in CircleCI to be able for google store
crowdbotics/react-native-scaffold pull request #186
Opened 2020-08-14 16:26 UTC by tan-duong

- update circleCI to create android app bundle (AAB) along with APK for appetize.io
- update scaffold to have target api level 29 and configure to be ready for AAB build

2020-08-18 22:02 UTC, tan-duong commented
Dan, started a discussion for upload key on slack

2020-10-02 18:28 UTC, driverdan requested changes

2020-10-02 18:29 UTC, driverdan commented
I've tested and confirmed this works. Once `.gitignore` is fixed I will approve.

2020-10-05 21:45 UTC, tan-duong commented on {{cookiecutter.project_slug}}/.gitignore
> +!upload-key.keystore
okay

2020-10-06 13:21 UTC, driverdan approved these changes

2020-10-06 13:21 UTC, merged